[package]
name = "phpdoc-parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"

[dependencies]
lazy_static = "1.4.0"
regex = "1.9.3"

[dev-dependencies]
pretty_assertions = "1.4.0"
